//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class STATUS
{

    private string cODEField;

    private string sEVERITYField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CODE
    {
        get
        {
            return this.cODEField;
        }
        set
        {
            this.cODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SEVERITY
    {
        get
        {
            return this.sEVERITYField;
        }
        set
        {
            this.sEVERITYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class OFX
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BANKMSGSRSV1", typeof(OFXBANKMSGSRSV1), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("SIGNONMSGSRSV1", typeof(OFXSIGNONMSGSRSV1), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("STATUS", typeof(STATUS))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXBANKMSGSRSV1
{

    private OFXBANKMSGSRSV1STMTTRNRS[] sTMTTRNRSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STMTTRNRS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OFXBANKMSGSRSV1STMTTRNRS[] STMTTRNRS
    {
        get
        {
            return this.sTMTTRNRSField;
        }
        set
        {
            this.sTMTTRNRSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXBANKMSGSRSV1STMTTRNRS
{

    private string tRNUIDField;

    private STATUS[] sTATUSField;

    private OFXBANKMSGSRSV1STMTTRNRSSTMTRS[] sTMTRSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRNUID
    {
        get
        {
            return this.tRNUIDField;
        }
        set
        {
            this.tRNUIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STATUS")]
    public STATUS[] STATUS
    {
        get
        {
            return this.sTATUSField;
        }
        set
        {
            this.sTATUSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STMTRS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OFXBANKMSGSRSV1STMTTRNRSSTMTRS[] STMTRS
    {
        get
        {
            return this.sTMTRSField;
        }
        set
        {
            this.sTMTRSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRS
{

    private string cURDEFField;

    private OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKACCTFROM[] bANKACCTFROMField;

    private OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLIST[] bANKTRANLISTField;

    private OFXBANKMSGSRSV1STMTTRNRSSTMTRSLEDGERBAL[] lEDGERBALField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CURDEF
    {
        get
        {
            return this.cURDEFField;
        }
        set
        {
            this.cURDEFField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BANKACCTFROM", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKACCTFROM[] BANKACCTFROM
    {
        get
        {
            return this.bANKACCTFROMField;
        }
        set
        {
            this.bANKACCTFROMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BANKTRANLIST", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLIST[] BANKTRANLIST
    {
        get
        {
            return this.bANKTRANLISTField;
        }
        set
        {
            this.bANKTRANLISTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LEDGERBAL", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OFXBANKMSGSRSV1STMTTRNRSSTMTRSLEDGERBAL[] LEDGERBAL
    {
        get
        {
            return this.lEDGERBALField;
        }
        set
        {
            this.lEDGERBALField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKACCTFROM
{

    private string bANKIDField;

    private string aCCTIDField;

    private string aCCTTYPEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BANKID
    {
        get
        {
            return this.bANKIDField;
        }
        set
        {
            this.bANKIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACCTID
    {
        get
        {
            return this.aCCTIDField;
        }
        set
        {
            this.aCCTIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACCTTYPE
    {
        get
        {
            return this.aCCTTYPEField;
        }
        set
        {
            this.aCCTTYPEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLIST
{

    private string dTSTARTField;

    private string dTENDField;

    private OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLISTSTMTTRN[] sTMTTRNField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DTSTART
    {
        get
        {
            return this.dTSTARTField;
        }
        set
        {
            this.dTSTARTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DTEND
    {
        get
        {
            return this.dTENDField;
        }
        set
        {
            this.dTENDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STMTTRN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLISTSTMTTRN[] STMTTRN
    {
        get
        {
            return this.sTMTTRNField;
        }
        set
        {
            this.sTMTTRNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLISTSTMTTRN
{

    private string tRNTYPEField;

    private string dTPOSTEDField;

    private string tRNAMTField;

    private string mEMOField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRNTYPE
    {
        get
        {
            return this.tRNTYPEField;
        }
        set
        {
            this.tRNTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DTPOSTED
    {
        get
        {
            return this.dTPOSTEDField;
        }
        set
        {
            this.dTPOSTEDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRNAMT
    {
        get
        {
            return this.tRNAMTField;
        }
        set
        {
            this.tRNAMTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MEMO
    {
        get
        {
            return this.mEMOField;
        }
        set
        {
            this.mEMOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSLEDGERBAL
{

    private string bALAMTField;

    private string dTASOFField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BALAMT
    {
        get
        {
            return this.bALAMTField;
        }
        set
        {
            this.bALAMTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DTASOF
    {
        get
        {
            return this.dTASOFField;
        }
        set
        {
            this.dTASOFField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXSIGNONMSGSRSV1
{

    private OFXSIGNONMSGSRSV1SONRS[] sONRSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SONRS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OFXSIGNONMSGSRSV1SONRS[] SONRS
    {
        get
        {
            return this.sONRSField;
        }
        set
        {
            this.sONRSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class OFXSIGNONMSGSRSV1SONRS
{

    private string dTSERVERField;

    private string lANGUAGEField;

    private STATUS[] sTATUSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DTSERVER
    {
        get
        {
            return this.dTSERVERField;
        }
        set
        {
            this.dTSERVERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LANGUAGE
    {
        get
        {
            return this.lANGUAGEField;
        }
        set
        {
            this.lANGUAGEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STATUS")]
    public STATUS[] STATUS
    {
        get
        {
            return this.sTATUSField;
        }
        set
        {
            this.sTATUSField = value;
        }
    }
}
